/*
 * Copyright 2013 Google Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.grafika;

// 📚 导入需要的类库
import android.app.Activity;                 // 📱 Activity：Android活动基类
import android.app.AlertDialog;              // 💬 AlertDialog：对话框
import android.content.Context;              // 📱 Context：上下文
import android.content.DialogInterface;      // 💬 DialogInterface：对话框接口
import android.os.AsyncTask;                 // ⚙️ AsyncTask：异步任务
import android.util.Log;                     // 📝 Log：日志工具
import android.widget.ProgressBar;           // 📊 ProgressBar：进度条
import android.widget.TextView;             // 📝 TextView：文本视图

import java.io.File;                         // 📁 File：文件类
import java.util.ArrayList;                  // 📦 ArrayList：动态数组
import com.google.grafika.R;                 // 🎨 R：资源文件

/**
 * Manages content generated by the app.
 * <p>
 * [ Originally this was going to prepare stuff on demand, but it's easier to just
 * create it all up front on first launch. ]
 * <p>
 * Class is thread-safe.
 * 
 * 📦 管理应用生成的内容
 * 💡 原本打算按需准备内容，但在首次启动时全部创建更简单
 * 🔒 这个类是线程安全的
 */
public class ContentManager {
    // 🏷️ TAG：日志标签
    private static final String TAG = MainActivity.TAG;

    // 📋 Enumerated content tags.  These are used as indices into the mContent ArrayList,
    //    so don't make them sparse.
    // 📋 枚举的内容标签，用作mContent ArrayList的索引，所以不要使它们稀疏
    // 📝 TODO: consider using String tags and a HashMap?  prepare() is currently fragile,
    //          depending on the movies being added in tag-order.  Could also just use a plain array.
    // 📝 待办：考虑使用String标签和HashMap？prepare()目前很脆弱，
    //          依赖于按标签顺序添加电影。也可以使用普通数组。
    
    // 🎬 内容标签常量
    public static final int MOVIE_EIGHT_RECTS = 0;   // 🎬 八个矩形的视频
    public static final int MOVIE_SLIDERS = 1;       // 🎬 滑块视频

    // 📋 所有标签数组
    private static final int[] ALL_TAGS = new int[] {
            MOVIE_EIGHT_RECTS,    // 🎬 八个矩形的视频
            MOVIE_SLIDERS         // 🎬 滑块视频
    };

    // 🔒 Housekeeping.
    // 🔒 内务管理变量
    private static final Object sLock = new Object();     // 🔒 同步锁
    private static ContentManager sInstance = null;       // 📦 单例实例

    // 📊 成员变量
    private boolean mInitialized = false;                 // ✅ 是否已初始化
    private File mFilesDir;                               // 📁 文件目录
    private ArrayList<Content> mContent;                  // 📦 内容列表

    /**
     * Returns the singleton instance.
     * 
     * 📤 获取单例实例
     * 💡 使用双重检查锁定确保线程安全
     */
    public static ContentManager getInstance() {
        // 🔒 sLock: 全局同步锁对象
        //    作用：确保多线程环境下单例创建的线程安全
        //    使用时机：每次获取实例时加锁，防止并发创建多个实例
        synchronized (sLock) {
            // 🔍 sInstance: ContentManager 的全局唯一实例
            //    作用：单例模式的核心引用，全局共享
            //    使用时机：首次调用时创建，后续直接返回
            if (sInstance == null) {
                // 📦 创建新的 ContentManager 实例
                //    作用：懒加载，仅在首次访问时创建
                sInstance = new ContentManager();
            }
            // 📤 返回全局唯一实例
            return sInstance;
        }
    }

    // 🔒 私有构造函数，防止外部实例化
    // 💡 为什么定义：单例模式要求外部不能直接new，只能通过getInstance()
    // 💡 作用：确保全局只有一个ContentManager实例
    // 💡 使用时机：被getInstance()内部调用创建唯一实例
    private ContentManager() {}

    /**
     * 初始化ContentManager
     * 
     * @param context 上下文对象
     */
    public static void initialize(Context context) {
        // 📦 mgr: 获取全局单例实例
        //    作用：获取 ContentManager 的唯一实例进行初始化
        //    使用时机：App 启动时调用，准备文件目录和内容列表
        ContentManager mgr = getInstance();

        // 🔒 sLock: 全局同步锁
        //    作用：防止多个线程同时初始化，避免重复创建内容列表
        synchronized (sLock) {
            // 🔍 mInitialized: 初始化完成标志
            //    作用：防止重复初始化，确保只初始化一次
            //    使用时机：检查是否已完成初始化
            if (!mgr.mInitialized) {
                // 📁 mFilesDir: 应用内部文件存储目录
                //    作用：存放生成的视频文件（如 gen-eight-rects.mp4）
                //    使用时机：创建视频文件时作为父目录传入 getPath()
                mgr.mFilesDir = context.getFilesDir();

                // 📦 mContent: 内容列表（ArrayList<Content>）
                //    作用：按标签索引存储已生成的视频内容对象
                //    使用时机：prepare() 中添加内容，getContent() 中读取内容
                mgr.mContent = new ArrayList<Content>();

                // ✅ mInitialized: 标记初始化完成
                //    作用：后续调用 initialize() 时跳过重复初始化
                mgr.mInitialized = true;
            }
        }
    }

    /**
     * Returns true if all of the content has been created.
     * <p>
     * If this returns false, call createAll.
     * 
     * 🔍 检查所有内容是否已创建
     * 💡 如果返回false，需要调用createAll创建内容
     * 
     * @param unused 未使用的参数
     * @return true表示所有内容已创建
     */
    public boolean isContentCreated(@SuppressWarnings("unused") Context unused) {
        // 🔄 i: ALL_TAGS 数组的循环索引
        //    作用：遍历所有内容标签（MOVIE_EIGHT_RECTS=0, MOVIE_SLIDERS=1）
        //    使用时机：每次循环递增，检查对应标签的文件是否存在
        for (int i = 0; i < ALL_TAGS.length; i++) {
            // 📁 file: 指定标签对应的视频文件路径
            //    作用：获取该内容在本地存储的完整文件路径
            //    使用时机：检查文件是否可读来判断内容是否已生成
            File file = getPath(i);

            // 🔍 file.canRead(): 检查文件是否可读（存在且有读权限）
            //    作用：判断该内容是否已成功生成并保存
            //    使用时机：任何一个文件不可读则立即返回 false
            if (!file.canRead()) {
                // 📝 记录哪个文件缺失，便于调试
                Log.d(TAG, "Can't find readable " + file);
                // ❌ 发现文件不存在或不可读，内容未全部创建
                return false;
            }
        }
        // ✅ 所有文件都存在且可读，内容已全部创建
        return true;
    }

    /**
     * Creates all content, overwriting any existing entries.
     * <p>
     * Call from main UI thread.
     * 
     * 🏗️ 创建所有内容，覆盖任何现有条目
     * 💡 必须从主UI线程调用
     * 
     * @param caller 调用者Activity
     */
    public void createAll(Activity caller) {
        // 📦 caller: 调用者Activity实例
        //    为什么定义：需要Activity来显示进度对话框
        //    作用：作为Context传入prepareContent，用于UI操作
        //    使用时机：传入prepareContent显示进度和错误对话框
        // 📦 ALL_TAGS: 所有内容标签数组（MOVIE_EIGHT_RECTS=0, MOVIE_SLIDERS=1）
        //    为什么定义：需要一次性准备所有视频内容
        //    作用：指定要生成的视频类型列表
        //    使用时机：传入prepareContent决定生成哪些视频
        prepareContent(caller, ALL_TAGS);
    }

    /**
     * Prepares the specified content.  For example, if the caller requires a movie that doesn't
     * exist, this will post a progress dialog and generate the movie.
     * <p>
     * Call from main UI thread.  This returns immediately.  Content generation continues
     * on a background thread.
     * 
     * 🏗️ 准备指定的内容
     * 💡 例如，如果调用者需要不存在的视频，会显示进度对话框并生成视频
     * 💡 必须从主UI线程调用，立即返回，内容生成在后台线程继续
     * 
     * @param caller 调用者Activity
     * @param tags 要准备的内容标签数组
     */
    public void prepareContent(Activity caller, int[] tags) {
        // 📢 builder: 进度对话框的构建器
        //    作用：创建显示内容生成进度的 AlertDialog
        //    使用时机：在异步任务开始前显示，告知用户正在准备内容
        AlertDialog.Builder builder = WorkDialog.create(caller, R.string.preparing_content);

        // 🚫 setCancelable(false): 禁止用户取消对话框
        //    作用：防止用户在内容生成过程中关闭对话框导致数据不完整
        builder.setCancelable(false);

        // 📢 dialog: 实际显示的进度对话框
        //    作用：展示给用户的进度 UI，包含进度条和文字说明
        //    使用时机：异步任务完成后在 onPostExecute 中关闭
        AlertDialog dialog = builder.show();

        // ⚙️ genTask: 异步内容生成任务
        //    作用：在后台线程中生成视频内容，避免阻塞 UI 线程
        //    使用时机：创建后立即 execute() 开始执行
        GenerateTask genTask = new GenerateTask(caller, dialog, tags);

        // ▶️ 启动异步任务，开始后台生成内容
        //    作用：触发 doInBackground() 在后台线程执行内容生成
        genTask.execute();
    }

    /**
     * Returns the specified item.
     * 
     * 📤 获取指定的内容项
     * 
     * @param tag 内容标签
     * @return 内容对象
     */
    public Content getContent(int tag) {
        // 🔒 使用同步锁确保线程安全
        synchronized (mContent) {
            // 📤 返回指定标签的内容
            return mContent.get(tag);
        }
    }

    /**
     * Prepares the specified item.
     * <p>
     * This may be called from the async task thread.
     */
    private void prepare(ProgressUpdater prog, int tag) {
        // 🎬 movie: 生成的视频内容对象
        //    💡 为什么定义：需要一个 GeneratedMovie 实例来执行视频编码和文件写入
        //    💡 作用：持有编码后的视频数据，实现 Content 接口
        //    💡 使用时机：根据 tag 创建对应类型的视频，生成后添加到 mContent 列表
        GeneratedMovie movie;

        // 🔀 tag: 内容标签，决定生成哪种视频
        //    作用：分支选择创建 MovieEightRects 还是 MovieSliders
        switch (tag) {
            // 🔀 case MOVIE_EIGHT_RECTS (tag=0)：八矩形视频分支
            // 💡 为什么分支：根据标签类型创建对应的视频内容对象
            case MOVIE_EIGHT_RECTS:
                // 🎬 movie = new MovieEightRects()：创建八矩形视频实例
                // 💡 为什么创建：需要一个实现了 GeneratedMovie 的对象来生成视频
                // 💡 作用：持有编码器、EGL 上下文等视频生成所需的资源
                // 💡 使用时机：立即调用 create() 生成视频数据
                movie = new MovieEightRects();
                // 📁 getPath(tag): 获取该标签对应的文件路径（如 gen-eight-rects.mp4）
                // 🎬 movie.create(path, prog): 在当前线程中生成视频内容（耗时操作）
                // 💡 为什么调用：这是实际生成 MP4 文件的核心方法
                // 💡 作用：编码 32 帧 GL 动画数据并写入文件
                // 💡 使用时机：创建 movie 实例后立即调用
                movie.create(getPath(tag), prog);
                // 🔒 synchronized(mContent): 线程安全地添加内容到列表
                // 💡 为什么加锁：prepare() 在后台线程执行，mContent 可能被 UI 线程读取
                // 💡 作用：防止并发修改导致数据不一致
                // 💡 使用时机：视频生成完成后，写入列表前加锁
                synchronized (mContent) {
                    // 📦 mContent.add(tag, movie): 按标签索引添加视频内容
                    // 💡 为什么添加：后续 getContent(tag) 需要通过索引获取内容
                    // 💡 作用：将生成的视频对象存入全局内容列表
                    mContent.add(tag, movie);
                }
                // 🔚 break：退出 switch，处理下一个标签
                break;
            // 🔀 case MOVIE_SLIDERS (tag=1)：滑块视频分支
            // 💡 为什么分支：根据标签类型创建对应的视频内容对象
            case MOVIE_SLIDERS:
                // 🎬 movie = new MovieSliders()：创建滑块视频实例
                // 💡 为什么创建：需要一个实现了 GeneratedMovie 的对象来生成视频
                // 💡 作用：持有编码器、EGL 上下文等视频生成所需的资源
                movie = new MovieSliders();
                // 📁 getPath(tag): 获取该标签对应的文件路径（如 gen-sliders.mp4）
                // 🎬 movie.create(path, prog): 在当前线程中生成视频内容（耗时操作）
                // 💡 为什么调用：这是实际生成 MP4 文件的核心方法
                // 💡 作用：编码 240 帧 GL 动画数据（红/绿方块滑动）并写入文件
                movie.create(getPath(tag), prog);
                // 🔒 synchronized(mContent): 线程安全地添加内容到列表
                // 💡 为什么加锁：同上，防止并发修改
                synchronized (mContent) {
                    // 📦 mContent.add(tag, movie): 按标签索引添加视频内容
                    // 💡 为什么添加：后续 getContent(tag) 需要通过索引获取内容
                    mContent.add(tag, movie);
                }
                // 🔚 break：退出 switch
                break;
            // 🚨 default：未知标签分支
            // 💡 为什么需要：防御性编程，防止传入非法标签值
            default:
                // 🚨 throw RuntimeException：抛出运行时异常
                // 💡 为什么抛出：未知标签表示程序逻辑错误，应立即终止
                throw new RuntimeException("Unknown tag " + tag);
        }
    }

    /**
     * Returns the filename for the tag.
     * 📁 根据标签返回对应的文件名
     * 💡 作用：将内容标签映射到具体的MP4文件名
     * 💡 使用时机：创建文件路径和显示文件名时调用
     */
    private String getFileName(int tag) {
        // 🔀 tag: 内容标签，决定返回哪个文件名
        //    为什么定义：需要根据不同的内容类型返回对应的文件名
        //    作用：分支选择返回哪个MP4文件名
        //    使用时机：switch判断后返回对应字符串
        switch (tag) {
            // 🔀 case MOVIE_EIGHT_RECTS (tag=0)：八矩形视频
            // 💡 为什么分支：每个标签对应一个固定的文件名
            case MOVIE_EIGHT_RECTS:
                // 📁 返回八矩形视频的文件名 "gen-eight-rects.mp4"
                // 💡 为什么这个名字：描述性命名，表示由程序生成的八矩形动画
                // 💡 作用：供 getPath() 拼接完整路径
                return "gen-eight-rects.mp4";
            // 🔀 case MOVIE_SLIDERS (tag=1)：滑块视频
            // 💡 为什么分支：每个标签对应一个固定的文件名
            case MOVIE_SLIDERS:
                // 📁 返回滑块视频的文件名 "gen-sliders.mp4"
                // 💡 为什么这个名字：描述性命名，表示由程序生成的滑块动画
                // 💡 作用：供 getPath() 拼接完整路径
                return "gen-sliders.mp4";
            // 🚨 default：未知标签
            // 💡 为什么需要：防御性编程，防止传入非法标签值
            default:
                // 🚨 throw RuntimeException：抛出运行时异常
                // 💡 为什么抛出：未知标签表示程序逻辑错误，应立即终止
                throw new RuntimeException("Unknown tag " + tag);
        }
    }

    /**
     * Returns the storage location for the specified item.
     */
    public File getPath(int tag) {
        return new File(mFilesDir, getFileName(tag));
    }

    public interface ProgressUpdater {
        /**
         * Updates a progress meter.
         * @param percent Percent completed (0-100).
         */
        void updateProgress(int percent);
    }

    /**
     * Performs generation of content on an async task thread.
     */
    private static class GenerateTask extends AsyncTask<Void, Integer, Integer>
            implements ProgressUpdater {
        // ----- accessed from UI thread -----
        private final Context mContext;
        private final AlertDialog mPrepDialog;
        private final ProgressBar mProgressBar;

        // ----- accessed from async thread -----
        private int mCurrentIndex;

        // ----- accessed from both -----
        private final int[] mTags;
        private volatile RuntimeException mFailure;


        /**
         * GenerateTask构造函数
         * 💡 作用：初始化异步任务的上下文、对话框和标签数组
         * 💡 使用时机：prepareContent()中创建GenerateTask实例时调用
         * 
         * @param context 上下文对象，用于资源访问
         * @param dialog 进度对话框，显示生成进度
         * @param tags 要生成的内容标签数组
         */
        public GenerateTask(Context context, AlertDialog dialog, int[] tags) {
            // 📦 mContext: Activity上下文对象
            //    为什么定义：需要Context来访问资源字符串和显示错误对话框
            //    作用：持有Activity引用，用于UI相关操作
            //    使用时机：showFailureDialog()中显示错误对话框时使用
            mContext = context;
            // 📢 mPrepDialog: 进度对话框引用
            //    为什么定义：需要在进度更新和任务完成时操作对话框
            //    作用：显示内容生成进度，完成后关闭
            //    使用时机：onProgressUpdate()更新进度，onPostExecute()关闭
            mPrepDialog = dialog;
            // 📋 mTags: 内容标签数组
            //    为什么定义：需要知道要生成哪些视频内容
            //    作用：存储MOVIE_EIGHT_RECTS和MOVIE_SLIDERS等标签
            //    使用时机：doInBackground()中循环遍历生成内容
            mTags = tags;
            // 📊 mProgressBar: 进度条控件
            //    为什么定义：需要更新进度条显示生成进度
            //    作用：可视化显示内容生成的总体进度
            //    使用时机：onProgressUpdate()中设置进度值
            mProgressBar = (ProgressBar) mPrepDialog.findViewById(R.id.work_progress);
            // 📊 设置进度条最大值 = 标签数量 × 100
            //    为什么这样设置：每个标签占100个进度单位，便于精确显示
            //    作用：总体进度 = 标签索引 × 100 + 当前标签进度百分比
            //    使用时机：构造函数中初始化，确定进度条范围
            mProgressBar.setMax(tags.length * 100);
        }

        @Override // async task thread
        // 💡 @Override：重写 AsyncTask 的 doInBackground 方法
        // 💡 作用：在后台线程中执行内容生成任务
        // 💡 使用时机：AsyncTask.execute() 后自动调用
        protected Integer doInBackground(Void... params) {
            // 📦 contentManager: 获取全局单例实例
            // 💡 为什么定义：需要调用单例的prepare()方法生成内容
            // 💡 作用：持有ContentManager的唯一实例引用
            // 💡 使用时机：在后台线程中调用prepare()生成视频内容
            ContentManager contentManager = ContentManager.getInstance();

            // 📝 记录后台任务开始执行
            Log.d(TAG, "doInBackground...");

            // 🔄 i: 当前正在处理的内容标签索引
            // 💡 为什么定义：需要遍历mTags数组，逐个生成内容
            // 💡 作用：标识当前正在生成第几个视频内容
            // 💡 使用时机：在循环中更新mCurrentIndex和调用prepare()
            for (int i = 0; i < mTags.length; i++) {
                // 📍 mCurrentIndex: 记录当前处理到第几个标签
                // 💡 为什么定义：updateProgress()需要知道当前是第几个任务
                // 💡 作用：供onProgressUpdate()计算总体进度条位置
                // 💡 使用时机：每次循环开始时更新，供进度回调使用
                mCurrentIndex = i;

                // 📊 通知UI当前项开始生成（进度0%）
                // 💡 为什么调用：让UI显示当前正在生成的文件名
                // 💡 作用：触发onProgressUpdate()更新界面显示
                // 💡 使用时机：每个新内容项开始生成前调用
                updateProgress(0);

                // 🔒 try：开始异常捕获块
                // 💡 为什么使用：视频生成可能因编码器错误、磁盘不足等原因抛异常
                try {
                    // 🎬 contentManager.prepare(this, mTags[i])：调用 prepare() 生成指定标签的内容
                    // 💡 为什么调用：这是实际执行视频生成的核心方法
                    // 💡 作用：根据标签类型创建 MovieEightRects 或 MovieSliders 并编码写入文件
                    // 💡 使用时机：在后台线程中逐个生成视频内容
                    contentManager.prepare(this, mTags[i]);
                // 🔒 catch (RuntimeException re)：捕获运行时异常
                // 💡 为什么捕获：内容生成失败时需要保存错误信息供 UI 线程显示
                } catch (RuntimeException re) {
                    // 🚨 mFailure: 记录生成失败的异常
                    // 💡 为什么定义：需要保存异常信息供UI线程显示错误
                    // 💡 作用：存储异常对象，在onPostExecute()中显示错误对话框
                    // 💡 使用时机：任何内容生成失败时捕获并赋值
                    mFailure = re;
                    break;  // 🚪 发生异常立即退出循环，不再生成后续内容
                }

                // 📊 当前项生成完成，通知UI进度100%
                // 💡 为什么调用：让UI更新进度条显示该项完成
                // 💡 作用：触发onProgressUpdate()将进度条设到100%
                // 💡 使用时机：每个内容项成功生成后调用
                updateProgress(100);
            }

            // 🔍 检查是否有生成失败的内容
            if (mFailure != null) {
                // ⚠️ 内容生成失败，记录警告日志便于调试
                // 💡 为什么记录：方便开发者在logcat中定位问题
                Log.w(TAG, "Failed while generating content", mFailure);
            // 🔍 else：mFailure == null，表示所有内容生成成功
            // 💡 为什么检查：区分成功和失败两种结果
            } else {
                // ✅ 所有内容生成成功，记录完成日志
                // 💡 为什么记录：确认所有视频已生成完毕
                Log.d(TAG, "generation complete");
            }

            // 📤 返回值未使用，AsyncTask要求必须有返回值
            // 💡 为什么返回0：AsyncTask<Void, Integer, Integer>的泛型要求
            // 💡 作用：满足编译器要求，实际返回值被忽略
            // 💡 使用时机：doInBackground()结束时返回
            return 0;
        }

        @Override // async task thread
        public void updateProgress(int percent) {
            publishProgress(mCurrentIndex, percent);
        }

        @Override // UI thread
        // 💡 @Override：重写 AsyncTask 的 onProgressUpdate 方法
        // 💡 作用：在 UI 线程中更新进度条和文件名显示
        // 💡 使用时机：publishProgress() 被调用后自动触发
        protected void onProgressUpdate(Integer... progressArray) {
            // 📍 index: 当前正在生成的内容标签索引 (progressArray[0])
            // 💡 为什么定义：需要知道正在处理哪个视频，以便显示文件名
            // 💡 作用：标识当前正在生成的内容项序号
            // 💡 使用时机：在percent==0时用于获取文件名显示
            int index = progressArray[0];

            // 📊 percent: 当前内容的生成进度 (0~100) (progressArray[1])
            // 💡 为什么定义：需要知道单个视频的完成百分比
            // 💡 作用：表示当前视频内容的生成进度
            // 💡 使用时机：与index组合计算总体进度条位置
            int percent = progressArray[1];

            //Log.d(TAG, "progress " + index + "/" + percent + " of " + mTags.length * 100);

            // 🔍 检查是否为新任务开始（进度0%）
            if (percent == 0) {
                // 📝 name: 进度对话框中的任务名称文本控件
                // 💡 为什么定义：需要更新显示当前正在生成的文件名
                // 💡 作用：持有TextView引用，用于设置文件名文本
                // 💡 使用时机：每个新文件开始生成时更新显示内容
                TextView name = (TextView) mPrepDialog.findViewById(R.id.workJobName_text);

                // 📋 获取当前标签对应的文件名并显示
                // 💡 为什么调用：让用户知道当前正在生成哪个文件
                // 💡 作用：将文件名（如"gen-eight-rects.mp4"）显示给用户
                // 💡 使用时机：每个新内容项开始生成时
                name.setText(ContentManager.getInstance().getFileName(mTags[index]));
            }

            // 📊 设置进度条位置 = 当前标签索引 × 100 + 当前百分比
            // 💡 为什么这样计算：总体进度 = (index * 100 + percent)
            // 💡 作用：在多个内容项时显示整体进度
            // 💡 使用时机：每次进度更新时刷新进度条
            // 💡 示例：2个标签，第一个完成50% → 进度 = 0*100+50 = 50
            // 💡 示例：2个标签，第一个完成100%，第二个30% → 进度 = 1*100+30 = 130
            mProgressBar.setProgress(index * 100 + percent);
        }

        @Override // UI thread
        // 💡 @Override：重写 AsyncTask 的 onPostExecute 方法
        // 💡 作用：在 UI 线程中处理任务完成后的操作（关闭对话框、显示错误）
        // 💡 使用时机：doInBackground() 返回后自动调用
        protected void onPostExecute(Integer result) {
            // 📝 Log.d：记录异步任务完成日志
            // 💡 为什么记录：方便开发者确认任务执行完毕
            Log.d(TAG, "onPostExecute -- dismss");

            // 📢 mPrepDialog: 进度对话框
            // 💡 为什么需要关闭：任务已完成，进度对话框不再需要
            // 💡 作用：关闭正在显示的进度提示，释放对话框资源
            // 💡 使用时机：内容生成完毕或失败后立即关闭
            mPrepDialog.dismiss();

            // 🔍 mFailure: 异常记录（非 null 表示生成失败）
            // 💡 为什么检查：需要判断内容生成是否出错
            // 💡 作用：决定是否显示错误对话框通知用户
            // 💡 使用时机：对话框关闭后检查，失败时弹出错误提示
            if (mFailure != null) {
                // 🚨 显示错误对话框，告知用户生成失败原因
                // 💡 为什么调用：需要让用户知道内容生成失败
                // 💡 作用：弹出错误提示，显示异常信息
                // 💡 使用时机：检测到mFailure不为null时调用
                showFailureDialog(mContext, mFailure);
            }
        }

        /**
         * Posts an error dialog, including the message from the failure exception.
         * 📢 显示错误对话框，包含失败异常的消息
         */
        private void showFailureDialog(Context context, RuntimeException failure) {
            // 📢 builder: 错误对话框的构建器
            // 💡 为什么定义：需要构建并配置错误提示对话框
            // 💡 作用：持有AlertDialog.Builder引用，用于设置标题、消息、按钮等
            // 💡 使用时机：内容生成失败时创建并配置错误对话框
            AlertDialog.Builder builder = new AlertDialog.Builder(context);

            // 🏷️ 设置对话框标题（资源ID: contentGenerationFailedTitle）
            // 💡 为什么调用：让用户一眼看到这是错误提示
            // 💡 作用：设置对话框标题文字为"内容生成失败"
            // 💡 使用时机：创建builder后立即设置
            builder.setTitle(R.string.contentGenerationFailedTitle);

            // 📝 msg: 格式化后的错误信息字符串
            // 💡 为什么定义：需要将异常消息嵌入到友好的提示文本中
            // 💡 作用：存储用户可读的错误描述信息
            // 💡 使用时机：传入builder.setMessage()显示给用户
            String msg = context.getString(R.string.contentGenerationFailedMsg,
                    // 💡 failure.getMessage()：获取异常的错误消息文本
                    // 💡 为什么传入：将实际错误原因嵌入到用户友好的提示文字中
                    failure.getMessage());

            // 📋 setMessage(msg)：设置对话框正文内容
            // 💡 为什么调用：告知用户具体的错误原因
            // 💡 作用：将格式化的错误消息显示在对话框中
            // 💡 使用时机：设置标题后设置消息内容
            builder.setMessage(msg);

            // ✅ 设置"确定"按钮及其点击事件
            // 💡 为什么需要：用户需要一个方式关闭错误对话框
            // 💡 作用：创建确定按钮，点击后关闭对话框
            // 💡 使用时机：配置完消息后添加按钮
            builder.setPositiveButton(R.string.ok, new DialogInterface.OnClickListener() {
                // 💡 @Override：重写 OnClickListener 的 onClick 方法
                @Override
                // 💡 onClick(DialogInterface dialog, int id)：按钮点击回调
                // 💡 为什么实现：用户点击"确定"按钮时需要关闭对话框
                // 💡 作用：处理对话框按钮的点击事件
                public void onClick(DialogInterface dialog, int id) {
                    // 🗑️ dialog.dismiss()：关闭错误对话框
                    // 💡 为什么调用：用户点击确定后应该关闭对话框
                    // 💡 作用：移除对话框，释放资源
                    // 💡 使用时机：用户点击确定按钮时
                    dialog.dismiss();
                }
                // 💡 });：关闭匿名 OnClickListener 和 setPositiveButton 方法调用
            });
            // 🚫 setCancelable(false)：禁止点击外部关闭对话框
            // 💡 为什么调用：强制用户看到错误信息并点击"确定"
            // 💡 作用：防止用户误触外部区域跳过错误提示
            // 💡 使用时机：配置完按钮后设置
            builder.setCancelable(false);

            // 📢 AlertDialog dialog = builder.create()：构建错误对话框
            // 💡 为什么定义：需要持有对话框引用才能调用 show() 显示
            // 💡 作用：将配置好的 builder 构建成对话框对象
            // 💡 使用时机：builder 配置完成后创建
            AlertDialog dialog = builder.create();
            // 📢 dialog.show()：显示错误对话框给用户
            // 💡 为什么调用：让用户看到内容生成失败的错误信息
            // 💡 作用：将对话框呈现在屏幕上
            // 💡 使用时机：对话框创建后立即显示
            dialog.show();
        }
    }
}
